### ISSUE TITLE
Generated App Store icon is not assigned

### ISSUE THREAD

**Issue by PatrickNLT** [KrauseFx/fastlane-plugin-appicon#18]
4b282da0be90e18857bf0c961e2c2506cd80534d renamed the `ios-marketing` key to `ios_marketing`.

Unfortunately, this updates the idiom inside the `Contents.json` file as well, resulting in an unassigned icon in Xcode.

Could we consider reverting this commit?

**Comment by KrauseFx** [comment]
Oh, nice catch, thanks. Do you want to submit a PR reverting the commit? Ideally, the user can use `:ios_marketing`, and internally it gets mapped to the `-` version 👍

**Comment by GantMan** [comment]
this can be closed

**Comment by PatrickNLT** [comment]
Fixed in #21
