### ISSUE TITLE
Plugin always updated generated icons

### ISSUE THREAD

**Issue by tominsam** [KrauseFx/fastlane-plugin-appicon#19]
I'd like to check in the generated icons so that when I build the app for development it still gets an icon. But every time I run the plugin the generated icons are updated on disk - even the MD5 of the file changes, so my git client gets unhappy.

Would it be reasonable to only generate icons if the target file is either not present or older than the source file?

**Comment by KrauseFx** [comment]
Yeah, sounds like a great idea. How would the plugin know if something has changed though? Happy to review a PR for this 👍

**Comment by tominsam** [comment]
I'd naïvely thought "mtime" but of course git doesn't preserve mtime. Would it be weird/unsafe to write the MD5 of the source file into the `info` block in `contents.json`?

**Comment by KrauseFx** [comment]
Mh, I'm not sure, I guess it would work, but I'm not sure if people are happy about it
