### ISSUE TITLE
Remove transparency from source PNG

### ISSUE THREAD

**Issue by escobar5** [KrauseFx/fastlane-plugin-appicon#24]
As iOS icons cannot have transparency it would be nice to have an option to remove transparency from a source PNG, that way you could have the same source image for both iOS and Android, but iOS image could be [flattened](http://www.imagemagick.org/script/command-line-options.php#flatten) to remove transparent background.

**Comment by dthuering** [comment]
I have created a pull request for the change: #29

**Comment by KrauseFx** [comment]
Awesome, thanks. Fixed with https://github.com/KrauseFx/fastlane-plugin-appicon/pull/29

**Comment by KrauseFx** [comment]
Pushing a new release now
