### ISSUE TITLE
New 1024x1024 image needed

### ISSUE THREAD

**Issue by GantMan** [KrauseFx/fastlane-plugin-appicon#33]
Missing the new 
```json
    {
      "size" : "1024x1024",
      "idiom" : "ios-marketing",
      "filename" : "someImage.png",
      "scale" : "1x"
    }
```

this is required
![image](https://user-images.githubusercontent.com/997157/36133141-3b579d12-1041-11e8-8203-47f52b016b6e.png)

**Comment by felipeplets** [comment]
Hello @GantMan, 

In fact this is already implement back in September 2017 in #17 by @PatrickNLT .

You need to add the **ios_marketing** in the **appicon_devices** parameter.
For further details you can check the examples in the project README.md. 

All the best, 
Felipe

**Comment by GantMan** [comment]
Gotcha, thanks... one note.... If this is required no-matter the device, why isn't it added by default?

**Comment by felipeplets** [comment]
Hey @GantMan, that is a good question, in fact as the [idiom](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/ImageSetType.html#//apple_ref/doc/uid/TP40015170-CH25-SW2) on the Asset Catalog is different the user is able to define either via AppIcon plugin or another way if desired. For now seems to me it is just more flexible the way it is. Let's keep the issue open and see how other see it.
