### ISSUE TITLE
How to pass list of devices as arguments to the lane

### ISSUE THREAD

**Issue by ngouass** [KrauseFx/fastlane-plugin-appicon#41]
Hi, I don't know ruby language and I'm trying to find a way to pass list of devices as arguments since values are not string.

**current state**
```
lane :test1 do
  appicon(
      appicon_image_file: 'spec/fixtures/Themoji.png',
      appicon_devices: [:ipad, :iphone, :ios_marketing])
end
```

**expecting state**
```
lane :test1 do |options|
  appicon(
      appicon_image_file: 'spec/fixtures/Themoji.png',
      appicon_devices: options[:devices]
  )
end
```

**command**:
```
bundle exec fastlane test1 devices:"[:iphone, :ipad, :ios_marketing]"
```

Thanks.

**Comment by KrauseFx** [comment]
It's not possible to pass an array via the command line for now, sorry. You'll have to define it in your `Fastfile` for now, you could manually build something to parse the CLI options differently though, however it's out of the scope for this project. 

Assuming you have 2-3 configurations, it's probably easiest to just have multiple lanes each with a different list.

**Comment by ngouass** [comment]
@KrauseFx  thanks for this answer! it actually looks clean to separate them.

**Comment by lukasondrak96** [comment]
@KrauseFx Is this still true? You cannot pass an array via command line? Thanks

**Comment by madarasz** [comment]
@lukasondrak96 
[https://docs.fastlane.tools/actions/prompt/](https://docs.fastlane.tools/actions/prompt/)

> Arrays can be passed as a comma delimited string (e.g. param:"1,2,3").

**Comment by francardoso93** [comment]
That's how I've managed to do this:

```
lane :github_commit_and_pull_request do|options
       schemes_list = JSON.parse(options[:schemes_list])
       schemes_list.each do |scheme|
           ....
       end    
...
end
```

Call this lane with parameter value with a JSON array as  the string value:
 `bundle exec fastlane github_commit_and_pull_request schemes_list:'["test","test"]'`
