### ISSUE TITLE
Adaptive icon support?

### ISSUE THREAD

**Issue by drewandre** [KrauseFx/fastlane-plugin-appicon#42]
Thank you for such a fantastic plugin! Runs great for me on iOS and Android. I was wondering if there were any plans for [android adaptive icons?](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) Android SDK 26+ allows for these types of icons. Users can now choose their icon style (circle or square), and the icons generated by this plugin result in a small square icon within a white circle if the user has their icons set as circular (see photo).

<img width="245" alt="screen shot 2018-07-17 at 5 59 56 pm" src="https://user-images.githubusercontent.com/13245041/42847831-48b6b73a-89eb-11e8-9242-e8c65ef6b03f.png">

**Comment by KrauseFx** [comment]
Nothing planned, however feel free to fork the plugin and submit a PR if you're interested 👍

**Comment by RishabhTayal** [comment]
I would like to take a stab at it. @drewandre @KrauseFx should we add a new option called `adaptive_icon`? This would be a bool. If set to true, we will generate adaptive icons.

**Comment by marcoruggine** [comment]
Hi guys, any news on this? 
It's the only thing I'm missing to reach complete automation in building a new white-label app for my clients.

**Comment by RishabhTayal** [comment]
@marcoruggine I have a wip branch to implement this. Feel free to complete it if you can.

**Comment by marcoruggine** [comment]
@RishabhTayal unfortunately it's beyond my capabilities... otherwise I'd be glad to help!

**Comment by RishabhTayal** [comment]
@marcoruggine I will try to work on it if I get some time. Unfortunately I am swamped at the moment.

**Comment by marcoruggine** [comment]
@RishabhTayal I really appreciate. Thanks!

**Comment by josh-m-sharpe** [comment]
@RishabhTayal FYI: my hacky branch: https://github.com/josh-m-sharpe/fastlane-plugin-appicon/commit/0ebc583f1a14e39e9843f1d953b9407e4753a5c6 - handles both rounded and foreground images but shells out to convert instead of using MiniMagick.

I'll be using my fork for a bit to see how that works.  

I think we're using different logic and convert args.  For example... why are you calculating radius by  (R-2)/2 (https://github.com/RishabhTayal/fastlane-plugin-appicon/blob/android-rounded-icon/lib/fastlane/plugin/appicon/actions/android_appicon_action.rb#L71-L72) ?

**Comment by KevinColemanInc** [comment]
@KrauseFx Could we get one of these merged in or explain what needs to be fixed between these?

edit: I Just ran @josh-m-sharpe's branch it worked great!

**Comment by GazzaHazza** [comment]
Is there any progress on this? Would love this functionality

**Comment by CoenWarmer** [comment]
Sorry to bug, but is there any chance this could get merged? @KrauseFx @neonichu @joshdholtz @adrum? Thanks!

**Comment by joshdholtz** [comment]
Will get a release out later tonight!

**Comment by joshdholtz** [comment]
Will try to work on this later on this week!

**Comment by CoenWarmer** [comment]
Thank you @joshdholtz!

**Comment by smohadjer** [comment]
Why was this closed? Does Fastlane support adaptive icons with foreground and background layers now?
