### ISSUE TITLE
Generate Rounded Error

### ISSUE THREAD

**Issue by GantMan** [KrauseFx/fastlane-plugin-appicon#59]
I'm trying to use the new `generate_rounded: true`

But I get this error:
```
`gm mogrify -alpha transparent -background none -fill white -draw roundrectangle 1,1,190,190,95,95 /var/folders/jt/w7z_82ns5n7fj1_2xjgl6r180000gn/T/mini_magick20200712-72378-8r1mmy.png` failed with error: (MiniMagick::Error)
gm mogrify: Unrecognized option (-alpha).

```

<img width="1401" alt="Screen Shot 2020-07-12 at 11 00 42 PM" src="https://user-images.githubusercontent.com/997157/87269725-a672cf00-c493-11ea-8056-2802b8817879.png">

**Comment by dandre-hound** [comment]
I found [this](https://www.drupal.org/project/pdfpreview/issues/2324057) issue online which suggested the issue you (and myself) are seeing is only on older versions of ImageMagic. I re-ran `brew install imagemagick` (since I hadn't updated it in over a year) and it seemed to fix this issue.

**Comment by GantMan** [comment]
Ah yup!  Thanks!

Doing a fresh brew install fixed this for me - closing.
